### ISSUE TITLE
Reassign index.html url on Tomo server

### ISSUE THREAD

**Issue by sushant404** [TomoAnalytics/welcome#1]
Currently, tomo.humandatacommons.org renders an outdated index.html. Since we now have the first commit using the new CSS theme, we are ready to publish the new site.

**Comment by obinine** [comment]
Using the guide at https://www.sitepoint.com/deploying-a-django-app-with-mod_wsgi-on-ubuntu-14-04/ to set this up since it requires apache to use wsgi instead of the apache proxying that first came to mind as a solution. Seems a safer option.
